export { default as EquipmentTiming } from './EquipmentTiming.vue'
export { default as NewlyBuild } from './NewlyBuild.vue'
export { default as ParameterConfiguration } from './ParameterConfiguration.vue'
export { default as TaskList } from './TaskList.vue'
export { default as TimingResult } from './TimingResult.vue'
export { default as TripartitePlatform } from './TripartitePlatform.vue'
